package org.example.sires033;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-19T14:07:31.153+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "SIRES033", wsdlLocation = "../../../wsdl/SIRES033.WSDL", targetNamespace = "http://www.example.org/SIRES033/SIRES033") 
public class SIRES033_Service extends Service {
    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/SIRES033/SIRES033", "SIRES033");
    public final static QName LDAPCHSOAPServiceSIRES033 = new QName("http://www.example.org/SIRES033/SIRES033", "LDAPCH_SOAPService_SIRES033");
    static {
        URL url = null;
        try {
            url = new URL("../../../wsdl/SIRES033.WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIRES033_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "../../../wsdl/SIRES033.WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SIRES033_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIRES033_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIRES033_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SIRES033_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIRES033_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIRES033_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SIRES033
     */
    @WebEndpoint(name = "LDAPCH_SOAPService_SIRES033")
    public SIRES033 getLDAPCHSOAPServiceSIRES033() {
        return super.getPort(LDAPCHSOAPServiceSIRES033, SIRES033.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIRES033
     */
    @WebEndpoint(name = "LDAPCH_SOAPService_SIRES033")
    public SIRES033 getLDAPCHSOAPServiceSIRES033(WebServiceFeature... features) {
        return super.getPort(LDAPCHSOAPServiceSIRES033, SIRES033.class, features);
    }
}