CREATE TABLE "contact" (
	"department" VARCHAR(80) NULL DEFAULT NULL,
	"identitynumber__c" VARCHAR(255) NULL DEFAULT NULL,
	"typepointofdeliveryrelationship__c" VARCHAR(255) NULL DEFAULT NULL,
	"sf4twitter__twitter_follower_count__c" DOUBLE PRECISION NULL DEFAULT NULL,
	"ownerid" VARCHAR(18) NULL DEFAULT NULL,
	"sfid" VARCHAR(18) NULL DEFAULT NULL,
	"createdbyid" VARCHAR(18) NULL DEFAULT NULL,
	"repeatedcases__c" BOOLEAN NULL DEFAULT NULL,
	"contacttype__c" VARCHAR(255) NULL DEFAULT NULL,
	"isdeleted" BOOLEAN NULL DEFAULT NULL,
	"firstname" VARCHAR(40) NULL DEFAULT NULL,
	"concatenatecontacaddress__c" VARCHAR(1300) NULL DEFAULT NULL,
	"systemmodstamp" TIMESTAMP NULL,
	"sf4twitter__twitter_bio__c" VARCHAR(255) NULL DEFAULT NULL,
	"contactaddress__c" VARCHAR(18) NULL DEFAULT NULL,
	"sf4twitter__origin__c" VARCHAR(255) NULL DEFAULT NULL,
	"concatenatename__c" VARCHAR(1300) NULL DEFAULT NULL,
	"preferredchannelcontact__c" VARCHAR(255) NULL DEFAULT NULL,
	"secondaryphone__c" VARCHAR(40) NULL DEFAULT NULL,
	"id" INTEGER NOT NULL DEFAULT E'',
	"identifycertificatenumberseries__c" DOUBLE PRECISION NULL DEFAULT NULL,
	"_hc_lastop" VARCHAR(32) NULL DEFAULT NULL,
	"vip__c" BOOLEAN NULL DEFAULT NULL,
	"fatherslastname__c" VARCHAR(1300) NULL DEFAULT NULL,
	"companyid__c" VARCHAR(255) NULL DEFAULT NULL,
	"phone" VARCHAR(40) NULL DEFAULT NULL,
	"fullname__c" VARCHAR(1300) NULL DEFAULT NULL,
	"sf4twitter__fcbk_username__c" VARCHAR(255) NULL DEFAULT NULL,
	"relationshipdetail__c" VARCHAR(255) NULL DEFAULT NULL,
	"sf4twitter__influencer_type__c" VARCHAR(255) NULL DEFAULT NULL,
	"identitytype__c" VARCHAR(255) NULL DEFAULT NULL,
	"sf4twitter__influencer__c" VARCHAR(255) NULL DEFAULT NULL,
	"name" VARCHAR(121) NULL DEFAULT NULL,
	"account__company__c" VARCHAR(255) NULL DEFAULT NULL,
	"secondaryemail__c" VARCHAR(80) NULL DEFAULT NULL,
	"lastmodifiedbyid" VARCHAR(18) NULL DEFAULT NULL,
	"additionalphone__c" VARCHAR(40) NULL DEFAULT NULL,
	"mobilephone" VARCHAR(40) NULL DEFAULT NULL,
	"motherslastname__c" VARCHAR(255) NULL DEFAULT NULL,
	"accountid" VARCHAR(18) NULL DEFAULT NULL,
	"sf4twitter__twitter_user_id__c" VARCHAR(255) NULL DEFAULT NULL,
	"personsegment__c" VARCHAR(255) NULL DEFAULT NULL,
	"sf4twitter__contact_source__c" VARCHAR(80) NULL DEFAULT NULL,
	"_hc_err" TEXT NULL DEFAULT NULL,
	"longtel2__c" DOUBLE PRECISION NULL DEFAULT NULL,
	"sf4twitter__twitter_username__c" VARCHAR(50) NULL DEFAULT NULL,
	"jobemail__c" VARCHAR(80) NULL DEFAULT NULL,
	"sf4twitter__fcbk_user_id__c" VARCHAR(255) NULL DEFAULT NULL,
	"masterrecordid" VARCHAR(18) NULL DEFAULT NULL,
	"email" VARCHAR(80) NULL DEFAULT NULL,
	"associatedaccounttype__c" VARCHAR(1300) NULL DEFAULT NULL,
	"createddate" TIMESTAMP NULL,
	"birthdate" DATE NULL DEFAULT NULL,
	UNIQUE INDEX "UNIQUE" ("sfid")
)
;

CREATE SEQUENCE contact_id_seq MINVALUE 0;
ALTER TABLE contact ALTER id SET DEFAULT nextval('contact_id_seq');
ALTER SEQUENCE contact_id_seq OWNED BY contact.id;