CREATE TABLE picklists (
	id			INTEGER NOT NULL,
	objeto		VARCHAR(255) NULL DEFAULT NULL,
	campo		VARCHAR(255) NULL DEFAULT NULL,
	codigo		VARCHAR(255) NULL DEFAULT NULL,
	valor		VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (id)
);