CREATE TABLE "pointofdelivery__c" (
	"municipalityallocation__c" VARCHAR(255) NULL DEFAULT NULL,
	"id" INTEGER NOT NULL DEFAULT E'',
	"repeatedcases__c" DOUBLE PRECISION NULL DEFAULT NULL,
	"createdbyid" VARCHAR(18) NULL DEFAULT NULL,
	"meterproperty__c" VARCHAR(255) NULL DEFAULT NULL,
	"transformertype__c" VARCHAR(255) NULL DEFAULT NULL,
	"block__c" VARCHAR(255) NULL DEFAULT NULL,
	"transformernumber__c" VARCHAR(255) NULL DEFAULT NULL,
	"servicetype__c" VARCHAR(255) NULL DEFAULT NULL,
	"opencases__c" BOOLEAN NULL DEFAULT NULL,
	"metermodel__c" VARCHAR(255) NULL DEFAULT NULL,
	"paymentprocess__c" BOOLEAN NULL DEFAULT NULL,
	"connectionstatus__c" VARCHAR(255) NULL DEFAULT NULL,
	"ballotname__c" VARCHAR(255) NULL DEFAULT NULL,
	"electrodependant__c" VARCHAR(255) NULL DEFAULT NULL,
	"sfid" VARCHAR(18) NULL DEFAULT NULL,
	"readingprocess__c" VARCHAR(255) NULL DEFAULT NULL,
	"grouptype__c" VARCHAR(255) NULL DEFAULT NULL,
	"createddate" TIMESTAMP NULL,
	"pointofdeliverystatus__c" VARCHAR(255) NULL DEFAULT NULL,
	"municipality__c" VARCHAR(1300) NULL DEFAULT NULL,
	"cutoffdate__c" TIMESTAMP NULL,
	"_hc_err" TEXT NULL DEFAULT NULL,
	"feedernumber__c" VARCHAR(255) NULL DEFAULT NULL,
	"lastmodifiedbyid" VARCHAR(18) NULL DEFAULT NULL,
	"condominiumsector__c" VARCHAR(255) NULL DEFAULT NULL,
	"metertype__c" VARCHAR(255) NULL DEFAULT NULL,
	"dangerzone__c" BOOLEAN NULL DEFAULT NULL,
	"isdeleted" BOOLEAN NULL DEFAULT NULL,
	"rate__c" VARCHAR(255) NULL DEFAULT NULL,
	"housetype__c" VARCHAR(255) NULL DEFAULT NULL,
	"disciplinarymeasure__c" VARCHAR(255) NULL DEFAULT NULL,
	"pointofdeliverynumber__c" VARCHAR(255) NULL DEFAULT NULL,
	"systemmodstamp" TIMESTAMP NULL,
	"dvnumberpointofdelivery__c" VARCHAR(255) NULL DEFAULT NULL,
	"segmenttype__c" VARCHAR(255) NULL DEFAULT NULL,
	"fullelectric__c" VARCHAR(255) NULL DEFAULT NULL,
	"customerrating__c" VARCHAR(255) NULL DEFAULT NULL,
	"readingtype__c" VARCHAR(255) NULL DEFAULT NULL,
	"meternumber__c" VARCHAR(255) NULL DEFAULT NULL,
	"rationingschedule__c" VARCHAR(255) NULL DEFAULT NULL,
	"name" VARCHAR(80) NULL DEFAULT NULL,
	"electricalsubstationconnection__c" VARCHAR(255) NULL DEFAULT NULL,
	"ownerid" VARCHAR(18) NULL DEFAULT NULL,
	"meterbrand__c" VARCHAR(255) NULL DEFAULT NULL,
	"cuttingdebt__c" BOOLEAN NULL DEFAULT NULL,
	"connectiontype__c" VARCHAR(255) NULL DEFAULT NULL,
	"navigationcontactid__c" VARCHAR(255) NULL DEFAULT NULL,
	"transformername__c" VARCHAR(255) NULL DEFAULT NULL,
	"vip__c" VARCHAR(255) NULL DEFAULT NULL,
	"networkconnectionpoint__c" VARCHAR(255) NULL DEFAULT NULL,
	"route__c" VARCHAR(11) NULL DEFAULT NULL,
	"_hc_lastop" VARCHAR(32) NULL DEFAULT NULL,
	"companyid__c" VARCHAR(255) NULL DEFAULT NULL,
	"pointofdeliveryaddress__c" VARCHAR(1300) NULL DEFAULT NULL,
	"detailaddress__c" VARCHAR(18) NULL DEFAULT NULL,
	"distributionaddress__c" VARCHAR(255) NULL DEFAULT NULL,
	UNIQUE INDEX "UNIQUE" ("sfid")
)
;

CREATE SEQUENCE pointofdelivery__c_id_seq MINVALUE 0;
ALTER TABLE pointofdelivery__c ALTER id SET DEFAULT nextval('pointofdelivery__c_id_seq');
ALTER SEQUENCE pointofdelivery__c_id_seq OWNED BY pointofdelivery__c.id;