CREATE TABLE "task" (
	"tasktype__c" VARCHAR(255) NULL DEFAULT NULL,
	"activitydate" DATE NULL DEFAULT NULL,
	"id" INTEGER NOT NULL DEFAULT E'',
	"whatid" VARCHAR(18) NULL DEFAULT NULL,
	"calldisposition" VARCHAR(255) NULL DEFAULT NULL,
	"casephone__c" VARCHAR(40) NULL DEFAULT NULL,
	"status" VARCHAR(40) NULL DEFAULT NULL,
	"description" TEXT NULL DEFAULT NULL,
	"_hc_lastop" VARCHAR(32) NULL DEFAULT NULL,
	"sfid" VARCHAR(18) NULL DEFAULT NULL,
	"createddate" TIMESTAMP NULL,
	"isdeleted" BOOLEAN NULL DEFAULT NULL,
	"subject" VARCHAR(255) NULL DEFAULT NULL,
	"priority" VARCHAR(40) NULL DEFAULT NULL,
	"account__company__c" VARCHAR(255) NULL DEFAULT NULL,
	"accountid" VARCHAR(18) NULL DEFAULT NULL,
	"systemmodstamp" TIMESTAMP NULL,
	"_hc_err" TEXT NULL DEFAULT NULL,
	"ownerid" VARCHAR(18) NULL DEFAULT NULL,
	"tasksubtype" VARCHAR(40) NULL DEFAULT NULL,
	"whoid" VARCHAR(18) NULL DEFAULT NULL,
	UNIQUE INDEX "UNIQUE" ("sfid")
)
;

CREATE SEQUENCE task_id_seq MINVALUE 0;
ALTER TABLE task ALTER id SET DEFAULT nextval('task_id_seq');
ALTER SEQUENCE task_id_seq OWNED BY task.id;