
package org.example.sieme009;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-19T14:07:28.519+02:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "MCD_Error", targetNamespace = "http://xmlns.endesa.com/CommonSchemas")
public class GetEventosRelFault extends Exception {
    private static final long serialVersionUID = -3450569150918548872L;
	
	private com.endesa.xmlns.commonschemas.MCDERROR mcdError;

    public GetEventosRelFault() {
        super();
    }
    
    public GetEventosRelFault(String message) {
        super(message);
    }
    
    public GetEventosRelFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetEventosRelFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError) {
        super(message);
        this.mcdError = mcdError;
    }

    public GetEventosRelFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError, Throwable cause) {
        super(message, cause);
        this.mcdError = mcdError;
    }

    public com.endesa.xmlns.commonschemas.MCDERROR getFaultInfo() {
        return this.mcdError;
    }
}
