package org.example.sieme009;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-19T14:07:28.554+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.example.org/SIEME009/SIEME009", name = "SIEME009")
@XmlSeeAlso({com.endesa.xmlns.commonschemas.ObjectFactory.class, org.example.sieme009_schema.ObjectFactory.class, com.endesa.xmlns.commonschemasneol.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIEME009 {

    @WebMethod(operationName = "GetEventosRel", action = "GetEventosRel")
    @WebResult(name = "GetEventosRelResponse", targetNamespace = "http://www.example.org/SIEME009_Schema/", partName = "response")
    public org.example.sieme009_schema.GetEventosRelResponseType getEventosRel(
        @WebParam(partName = "request", name = "GetEventosRelRequest", targetNamespace = "http://www.example.org/SIEME009_Schema/")
        org.example.sieme009_schema.GetEventosRelRequestType request
    ) throws GetEventosRelFault;
}
