
package org.example.sires033;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-19T14:07:31.068+02:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "MCD_Error", targetNamespace = "http://xmlns.endesa.com/CommonSchemas")
public class ConsultaDatosSuministroFault extends Exception {
	private static final long serialVersionUID = 7682144717639481083L;

	private com.endesa.xmlns.commonschemas.MCDERROR mcdError;

    public ConsultaDatosSuministroFault() {
        super();
    }
    
    public ConsultaDatosSuministroFault(String message) {
        super(message);
    }
    
    public ConsultaDatosSuministroFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ConsultaDatosSuministroFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError) {
        super(message);
        this.mcdError = mcdError;
    }

    public ConsultaDatosSuministroFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError, Throwable cause) {
        super(message, cause);
        this.mcdError = mcdError;
    }

    public com.endesa.xmlns.commonschemas.MCDERROR getFaultInfo() {
        return this.mcdError;
    }
}
