
package org.example.sieme002;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-31T14:33:39.671+01:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "MCD_Error", targetNamespace = "http://xmlns.endesa.com/CommonSchemas")
public class GetCalleFault extends Exception {
	private static final long serialVersionUID = 1L;

	private com.endesa.xmlns.commonschemas.MCDERROR mcdError;

    public GetCalleFault() {
        super();
    }
    
    public GetCalleFault(String message) {
        super(message);
    }
    
    public GetCalleFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetCalleFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError) {
        super(message);
        this.mcdError = mcdError;
    }

    public GetCalleFault(String message, com.endesa.xmlns.commonschemas.MCDERROR mcdError, Throwable cause) {
        super(message, cause);
        this.mcdError = mcdError;
    }

    public com.endesa.xmlns.commonschemas.MCDERROR getFaultInfo() {
        return this.mcdError;
    }
}
