package org.example.sieme009;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-19T14:07:28.582+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "SIEME009", wsdlLocation = "../../../wsdl/SIEME009.WSDL", targetNamespace = "http://www.example.org/SIEME009/SIEME009") 
public class SIEME009_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/SIEME009/SIEME009", "SIEME009");
    public final static QName LDAPCHSOAPServiceSIEME009 = new QName("http://www.example.org/SIEME009/SIEME009", "LDAPCH_SOAPService_SIEME009");
    static {
        URL url = null;
        try {
            url = new URL("../../../wsdl/SIEME009.WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIEME009_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "../../../wsdl/SIEME009.WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SIEME009_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIEME009_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIEME009_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SIEME009_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIEME009_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIEME009_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SIEME009
     */
    @WebEndpoint(name = "LDAPCH_SOAPService_SIEME009")
    public SIEME009 getLDAPCHSOAPServiceSIEME009() {
        return super.getPort(LDAPCHSOAPServiceSIEME009, SIEME009.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIEME009
     */
    @WebEndpoint(name = "LDAPCH_SOAPService_SIEME009")
    public SIEME009 getLDAPCHSOAPServiceSIEME009(WebServiceFeature... features) {
        return super.getPort(LDAPCHSOAPServiceSIEME009, SIEME009.class, features);
    }

}
